### ISSUE TITLE
How to select a BOM version?

### ISSUE THREAD

**Issue by sfc-gh-kleonhard** [jenkinsci/bom#2359]
### Describe your use-case which is not covered by existing documentation.

https://github.com/jenkinsci/bom#usage suggests:

```
After selecting your plugin’s LTS baseline:

<jenkins.version>2.387.3</jenkins.version>

just import the [latest BOM](https://github.com/jenkinsci/bom/releases) from that line:

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.jenkins.tools.bom</groupId>
            <artifactId>bom-2.387.x</artifactId>
            <version>…</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
```

`artifactid` is clear - select the version corresponding to the `jenkins.version` value. What about `version`? Is the suggestion to go to https://github.com/jenkinsci/bom/releases and select the latest release without regard for the jenkins.version?

I found this confusing. I think  a tweak would help greatly!

**Comment by MarkEWaite** [comment]
Thanks for the question.  I'm open to suggestions to increase the clarity.

> `artifactid` is clear - select the version corresponding to the `jenkins.version` value. What about `version`? Is the suggestion to go to https://github.com/jenkinsci/bom/releases and select the latest release without regard for the jenkins.version?
> 
> I found this confusing. I think a tweak would help greatly!

The `artifactId` should generally correspond to the `jenkins.version` defined in the `pom.xml` file.  If the `jenkins.version` is `2.361.4` then the `artifactId` should be `bom-2.361.x`.  If the `jenkins.version is `2.375.4`, then the `artifactId` should be `bom-2.375.x`.  If the `jenkins.version` is `2.387.3`, then the `artifactId` should be `bom-2.387.x`.

The correspondence between `artifactId` and `jenkins.version` is not strictly required, but is highly recommended.

The `release` should be the latest release for the `artifactId` they've selected.  For example, https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/tools/bom/ shows that the following latest releases:

* bom-2.346.x - 1763.v092b_8980a_f5e
* bom-2.361.x - 2102.v854b_fec19c92
* bom-2.375.x - 2198.v39c76fc308ca
* bom-2.387.x - 2312.v91115fa_5b_2b_6
* bom-2.401.x - 2312.v91115fa_5b_2b_6

The correspondence between `artifactId` and `version` is enforced by Maven.  If the plugin developer enters a release that does not exist for their line, compilation will fail because the bill of materials version they specified won't be found.

I'm open to suggestions that improve the clarity.  What do you recommend?

As another alternative, we could recommend that they use dependabot and rely on it to recommend the most recent release for the `jenkins.version` used in their plugin.

**Comment by sfc-gh-kleonhard** [comment]
Thanks Mark!

> The release should be the latest release for the artifactId they've selected.

That makes perfect sense to me. Given an artifactId, how do figure that out from https://github.com/jenkinsci/bom/releases? By looking at  https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/tools/bom/, it's easy to click on the artifact ID and identify the latest version.

Perhaps something along the lines of: import the latest BOM release for your selected Jenkins version by looking at the [BOM releases](https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/tools/bom/). To see the change log, look at the [releases](https://github.com/jenkinsci/bom/releases) on Github.

This would have gotten me there!

Are these versions connected at all to the parent POM version set in the `<parent>` section? org.jenkins-ci.plugins:plugin https://github.com/jenkinsci/plugin-pom/releases

**Comment by MarkEWaite** [comment]
I'll need to give some more thought to the phrasing.  Will look at it more later.

**Comment by MarkEWaite** [comment]
We discussed it in docs office hours (Asia) and think that there is a two-part approach.  One part is to add static examples for the older versions with descriptions that guide people why they might choose an older version.  For example:

## `bom-2.387.x` - Current recommendation for most development

insert example here (without a specific version)

## `bom-2.346.x` - Last Jenkins LTS to support Java 8

insert example here with a specific version

## `bom-2.361.x` - First Jenkins LTS to require Java 11 or newer

insert example here with a specific version

That layout would be the first step.

A second step would be to use `updatecli` or one of the other update tools to insert the most recent release into the example for the current recommendation.  Then the reader can copy and paste without any seearching.

**Comment by jetersen** [comment]
Would it not be better to update: https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ with an example of bom? 🤔

**Comment by MarkEWaite** [comment]
> Would it not be better to update: https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ with an example of bom? 🤔

That is a very good additional step.  I think that we can improve the clarity of the instructions in this repository and can add guidance on the plugin bill of materials to the "Choosing a Jenkins baseline" page.

**Comment by sfc-gh-kleonhard** [comment]
Thanks for jumping on this! I appreciate it. It has been fun knocking out a Jenkins plugin.

One more thought on the guidance page - in addition to the jenkins baseline version and BOM version, developers need to select a parent pom version: https://github.com/jenkinsci/plugin-pom/releases. If you're looking to document version selection in one place, add that to the list.

**Comment by MarkEWaite** [comment]
@StackScribe and @krisstern both felt that we should include a link to the [plugin bill of materials tutorial page](https://www.jenkins.io/doc/developer/tutorial-improve/use-plugin-bill-of-materials/) and to the README documentation in this repository in the page.

**Comment by MarkEWaite** [comment]
> @StackScribe and @krisstern both felt that we should include a link to the [plugin bill of materials tutorial page](https://www.jenkins.io/doc/developer/tutorial-improve/use-plugin-bill-of-materials/) and to the README documentation in this repository in the page.

Link to the BOM tutorial has been added in

* #2637
