### ISSUE TITLE
`CliGitAPIImplTest.test_list_branches` (& `JGitAPIImplTest`) failing

### ISSUE THREAD

**Issue by jglick** [jenkinsci/bom#638]
`test_list_branches` is failing in CI recently, e.g. https://github.com/jenkinsci/bom/runs/3445534428; most recent edit appears to be https://github.com/jenkinsci/git-client-plugin/commit/aaec01d5b2495f69957fef0200802a1e8eebbfb5

**Comment by MarkEWaite** [comment]
Thanks @jglick .  I believe that I've seen that as a flaky test that depends on a specific command line git version.  The CI agents have been updated to use command line git 2.33.0, so they now show the error.

**Comment by MarkEWaite** [comment]
I'm not sure what to do with that failure.  The test was last included in git client plugin 3.6.0.  Git client plugin 3.7.0 and later require Jenkins 2.263.1.

I could modify or remove the test in a branch of git client 2.6.0 to deliver a git client plugin 2.6.1 with the test fixed.  Any other suggestions?

I've created the [stable-3.6.x branch](https://github.com/jenkinsci/git-client-plugin/commits/stable-3.6.x), advanced it to the point where the issue is resolved, and made a few additional commits to use the most recent pom.xml settings, while removing any changes to `src/main` that were made after the release of git client plugin 3.6.1.  The [CI job](https://ci.jenkins.io/job/Plugins/job/git-client-plugin/job/stable-3.6.x/) for that branch is running now.  It passes tests on my Linux computer with command line git 2.33.0 installed.

**Comment by timja** [comment]
If it’s an old release we can just add it to the excludes file? https://github.com/jenkinsci/bom/blob/master/excludes.txt

With a TODO to drop it after that line is not supported

**Comment by jglick** [comment]
Ah I did not realize this failed only with older versions of `git-client`. In that case I think it is fine to just add it to the excludes. (Currently we do not have a line-specific excludes list.)
